apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wordpress
spec:
  secretName: wordpress-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fabadaword.press
  dnsNames:
    - www.fabadaword.press
  acme:
    config:
    - http01:
        ingress: wordpress
      domains:
      - fabadaword.press
      - www.fabadaword.press
