---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  mysql_user: ZmFiYWRlcnM=
  mysql_password: bGFfZmFiYWRhY29uZl9tb2xhX21vZ29sbG9u
  mysql_root_password: c3VwM3ItbTNnNC1zM2NyM3QtcDRzc3cwcmQ=
